"""Durable Edge/Cloud sync and remote action delivery."""

import sqlalchemy as sa
from alembic import op

revision = "0012_edge_cloud"
down_revision = "0011_auth"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_state",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("installation_id", sa.String(length=36), nullable=False),
        sa.Column("initialized", sa.Boolean(), nullable=False),
        sa.Column("last_sync_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=200), nullable=True),
        sa.Column("failures", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "mode IN ('standalone','edge','cloud')", name=op.f("ck_sync_state_mode")
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_sync_state_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_state")),
    )
    op.create_table(
        "edge_installations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("software_version", sa.String(length=50), nullable=True),
        sa.Column("runtime", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_edge_installations")),
    )
    op.create_table(
        "sync_outbox",
        sa.Column(
            "id",
            sa.BigInteger().with_variant(sa.Integer(), "sqlite"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("entity", sa.String(length=60), nullable=False),
        sa.Column("operation", sa.String(length=8), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_outbox")),
        sa.UniqueConstraint("event_id", name=op.f("uq_sync_outbox_event_id")),
    )
    op.create_index("ix_sync_outbox_priority_id", "sync_outbox", ["priority", "id"], unique=False)
    op.create_table(
        "sync_receipts",
        sa.Column("edge_id", sa.String(length=36), nullable=False),
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["edge_installations.id"],
            name=op.f("fk_sync_receipts_edge_id_edge_installations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("edge_id", "event_id", name=op.f("pk_sync_receipts")),
    )
    op.create_table(
        "sync_mappings",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("edge_id", sa.String(length=36), nullable=False),
        sa.Column("entity", sa.String(length=60), nullable=False),
        sa.Column("local_key", sa.String(length=160), nullable=False),
        sa.Column("cloud_key", sa.JSON(), nullable=False),
        sa.Column("cloud_id", sa.Integer(), nullable=True),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("deleted", sa.Boolean(), nullable=False),
        sa.Column("original", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["edge_installations.id"],
            name=op.f("fk_sync_mappings_edge_id_edge_installations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_mappings")),
        sa.UniqueConstraint(
            "edge_id", "entity", "local_key", name=op.f("uq_sync_mappings_edge_id")
        ),
    )
    op.create_index(op.f("ix_sync_mappings_edge_id"), "sync_mappings", ["edge_id"], unique=False)
    op.create_index("ix_sync_mappings_cloud", "sync_mappings", ["entity", "cloud_id"], unique=False)
    op.create_table(
        "remote_requests",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("edge_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.Integer(), nullable=False),
        sa.Column("command_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('command','acknowledge')", name=op.f("ck_remote_requests_kind")
        ),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["commands.id"],
            name=op.f("fk_remote_requests_command_id_commands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["edge_id"],
            ["edge_installations.id"],
            name=op.f("fk_remote_requests_edge_id_edge_installations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_remote_requests_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remote_requests")),
        sa.UniqueConstraint("command_id", name=op.f("uq_remote_requests_command_id")),
    )
    op.create_index(
        "ix_remote_requests_edge_status", "remote_requests", ["edge_id", "status"], unique=False
    )
    op.create_table(
        "remote_inbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("cloud_user_id", sa.Integer(), nullable=False),
        sa.Column("cloud_username", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("command_id", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["command_id"],
            ["commands.id"],
            name=op.f("fk_remote_inbox_command_id_commands"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_remote_inbox")),
        sa.UniqueConstraint("command_id", name=op.f("uq_remote_inbox_command_id")),
    )
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_commands_status"), "commands", type_="check")
    op.create_check_constraint(
        "status",
        "commands",
        "status IN ('PENDING_EDGE','DELIVERED','QUEUED','EXECUTING','VERIFYING','SUCCESS','FAILED','CANCELLED','EXPIRED')",
    )
    first, second = SYNC_FUNCTIONS.split("CREATE FUNCTION capture_sync_event", 1)
    op.execute(first)
    op.execute("CREATE FUNCTION capture_sync_event" + second)
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON locations FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON connections FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON devices FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON tags FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON dashboards FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON dashboard_widgets FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON dashboard_widget_tags FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON dashboard_widget_layouts FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON alarm_rules FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON automation_rules FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON automation_conditions FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON automation_actions FOR EACH ROW EXECUTE FUNCTION capture_sync_event('0')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON remote_inbox FOR EACH ROW EXECUTE FUNCTION capture_sync_event('1')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON commands FOR EACH ROW EXECUTE FUNCTION capture_sync_event('1')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON alarm_events FOR EACH ROW EXECUTE FUNCTION capture_sync_event('2')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON tag_current_values FOR EACH ROW EXECUTE FUNCTION capture_sync_event('3')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON connection_runtime FOR EACH ROW EXECUTE FUNCTION capture_sync_event('3')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON worker_runtime FOR EACH ROW EXECUTE FUNCTION capture_sync_event('3')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON automation_runtime FOR EACH ROW EXECUTE FUNCTION capture_sync_event('4')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON automation_executions FOR EACH ROW EXECUTE FUNCTION capture_sync_event('4')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON automation_execution_commands FOR EACH ROW EXECUTE FUNCTION capture_sync_event('4')"
    )
    op.execute(
        "CREATE TRIGGER sync_capture AFTER INSERT OR UPDATE OR DELETE ON tag_history FOR EACH ROW EXECUTE FUNCTION capture_sync_event('9')"
    )


def downgrade():
    op.execute("DROP TRIGGER sync_capture ON locations")
    op.execute("DROP TRIGGER sync_capture ON connections")
    op.execute("DROP TRIGGER sync_capture ON devices")
    op.execute("DROP TRIGGER sync_capture ON tags")
    op.execute("DROP TRIGGER sync_capture ON dashboards")
    op.execute("DROP TRIGGER sync_capture ON dashboard_widgets")
    op.execute("DROP TRIGGER sync_capture ON dashboard_widget_tags")
    op.execute("DROP TRIGGER sync_capture ON dashboard_widget_layouts")
    op.execute("DROP TRIGGER sync_capture ON alarm_rules")
    op.execute("DROP TRIGGER sync_capture ON automation_rules")
    op.execute("DROP TRIGGER sync_capture ON automation_conditions")
    op.execute("DROP TRIGGER sync_capture ON automation_actions")
    op.execute("DROP TRIGGER sync_capture ON remote_inbox")
    op.execute("DROP TRIGGER sync_capture ON commands")
    op.execute("DROP TRIGGER sync_capture ON alarm_events")
    op.execute("DROP TRIGGER sync_capture ON tag_current_values")
    op.execute("DROP TRIGGER sync_capture ON connection_runtime")
    op.execute("DROP TRIGGER sync_capture ON worker_runtime")
    op.execute("DROP TRIGGER sync_capture ON automation_runtime")
    op.execute("DROP TRIGGER sync_capture ON automation_executions")
    op.execute("DROP TRIGGER sync_capture ON automation_execution_commands")
    op.execute("DROP TRIGGER sync_capture ON tag_history")
    op.execute("DROP FUNCTION capture_sync_event()")
    op.execute("DROP FUNCTION sync_document(text, jsonb)")
    op.execute(
        "UPDATE commands SET status='EXPIRED', completed_at=now(), error_message='Cloud mode removed' WHERE status IN ('PENDING_EDGE','DELIVERED')"
    )
    op.drop_constraint(op.f("ck_commands_status"), "commands", type_="check")
    op.create_check_constraint(
        "status",
        "commands",
        "status IN ('QUEUED','EXECUTING','VERIFYING','SUCCESS','FAILED','CANCELLED','EXPIRED')",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("remote_inbox")
    op.drop_table("remote_requests")
    op.drop_table("sync_mappings")
    op.drop_table("sync_receipts")
    op.drop_table("sync_outbox")
    op.drop_table("edge_installations")
    op.drop_table("sync_state")
    # ### end Alembic commands ###


SYNC_FUNCTIONS = r"""
CREATE FUNCTION sync_document(entity text, doc jsonb) RETURNS jsonb LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE field text;
BEGIN
 doc := doc - 'requested_by' - 'acknowledged_by';
 IF entity = 'worker_runtime' THEN doc := doc - 'hostname' - 'serial_ports' - 'discovered_at' - 'discovery_error'; END IF;
 FOREACH field IN ARRAY ARRAY['value_numeric','requested_numeric','previous_numeric','verified_numeric','hysteresis'] LOOP
  IF doc ? field AND doc->field <> 'null'::jsonb THEN doc := jsonb_set(doc, ARRAY[field], to_jsonb(doc->>field)); END IF;
 END LOOP;
 RETURN doc;
END $$;
CREATE FUNCTION capture_sync_event() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE doc jsonb;
BEGIN
 IF (SELECT mode FROM sync_state WHERE id=1) IS DISTINCT FROM 'edge' THEN RETURN NULL; END IF;
 IF TG_OP='DELETE' AND TG_TABLE_NAME IN ('tag_history','commands','alarm_events','automation_executions','remote_inbox') THEN RETURN NULL; END IF;
 doc := sync_document(TG_TABLE_NAME, CASE WHEN TG_OP='DELETE' THEN to_jsonb(OLD) ELSE to_jsonb(NEW) END);
 INSERT INTO sync_outbox(event_id,entity,operation,priority,payload,created_at)
 VALUES(gen_random_uuid()::text,TG_TABLE_NAME,CASE WHEN TG_OP='DELETE' THEN 'delete' ELSE 'upsert' END,TG_ARGV[0]::int,doc,now());
 RETURN NULL;
END $$;
"""
